### ISSUE TITLE
devbetter on github

### ISSUE THREAD

**Issue by ardalis** [devbetter/git_test#1]
Hi! I'd like to set up an organization for my devbetter group here on GitHub, and ideally I'd like to use github.com/devbetter as its name. I notice you have the account but aren't terribly active. Would you be open to renaming yours so I could use it for my org? Thanks for your consideration and I would really appreciate it. Cheers!

**Comment by ardalis** [comment]
Do you check these?

**Comment by devbetter** [comment]
Sorry!
